---
name: GitHub hosted facter CI

on: [push]

jobs:
  linux:
    name: Run acceptance tests
    strategy:
      matrix:
#        os: [ubuntu-18.04, ubuntu-16.04, macos-10.15, windows-2016]
        os: [windows-2016]
#        os: [windows-2016, windows-2019]
    runs-on: ${{ matrix.os }}
    env:
      FACTER_3_ROOT: facter_3
      FACTER_4_ROOT: facter_4
      BEAKER_ROOT: beaker
      SHA: latest
      BEAKER_VERSION: 4.21.0

    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2
        with:
          path: facter_4

      - name: Clone facter 3 repo
        uses: actions/checkout@v2
        with:
          repository: puppetlabs/facter
          ref: skip_failures_on_ng
          path: facter_3

      - name: Clone custom beaker fork
        uses: actions/checkout@v2
        with:
          repository: mihaibuzgau/beaker
          ref: master
          path: beaker

      - name: Install Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Fix common Linux and MacOs permissions
        if: runner.os != 'Windows'
        run: sudo chmod a-w /opt

      - name: Fix Linux permissions
        if: runner.os == 'Linux'
        run: |
          sudo chmod a-w /home/runner /usr/share &&
          sudo chmod -R a-w /usr/share/rust /home/runner/.config

      - name: Fix ubuntu-16.04 permissions
        if: matrix.os == 'ubuntu-16.04'
        run: sudo chmod -R a-w /home/linuxbrew

      - name: Run acceptance tests on Linux like platform
        if: runner.os != 'Windows'
        run: sudo -E "PATH=$PATH" ruby $FACTER_4_ROOT/.github/actions/presuite.rb ${{ matrix.os }}

      - name: Run acceptance tests on Windows like platform
        if: runner.os == 'Windows'
        run: ruby $Env:FACTER_4_ROOT/.github/actions/presuite.rb ${{ matrix.os }}
